run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - stylecheck
    - gosec
    - unconvert
    - gocyclo
    - misspell
    - revive
    - exportloopref
    - predeclared

linters-settings:
  gocyclo:
    min-complexity: 20

  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true

  staticcheck:
    checks: ["all"]

  stylecheck:
    checks: ["all", "-ST1003"]  # Allow underscores in names for regional patterns

  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: false
      - name: var-naming
        disabled: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

    # Exclude known false positives
    - linters:
        - staticcheck
      text: "SA1019:"  # Ignore deprecation warnings for now

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
